version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 on the container
    volumes:
      - ./src:/var/www/html  # Mount the src folder into the container
    restart: always
